import { it } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { build } from 'vite';
interface BrowserQA {
  evaluate: <T = unknown>(expression: string) => Promise<T>;
  waitFor: (expression: string, timeout?: number) => Promise<void>;
  call: (method: string, params?: Record<string, unknown>) => Promise<unknown>;
  resize: (width: number, height: number) => Promise<void>;
  close: () => Promise<void>;
}
// CJS helper shared with the repeatable screenshot workflow.
const { openBrowser } = createRequire(path.join(__dirname,'renderer-polish.test.ts'))('../../scripts/browser-qa.cjs') as { openBrowser: (file: string, profile: string) => Promise<BrowserQA> };
it('renderer polish preserves drafts, keyboard menus, likes and responsive inspector behavior', { timeout: 45000 }, async (t) => {
  if (!existsSync(process.env.CHROME_BIN ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')) { t.skip('Chrome unavailable'); return; }
  const dir = mkdtempSync(path.join(tmpdir(),'musedesk-polish-'));
  let browser: BrowserQA | undefined;
  try {
    await build({root:path.resolve(__dirname,'../..'),logLevel:'silent',build:{outDir:dir,emptyOutDir:false}});
    const mock = readFileSync(path.resolve(__dirname,'../../scripts/mock-bridge.cjs'),'utf8').split('module.exports')[0];
    const html = readFileSync(path.join(dir,'index.html'),'utf8').replaceAll('"/assets/','"./assets/');
    const file = path.join(dir,'polish.html');
    writeFileSync(file,`<script>${mock}\nlocalStorage.clear();window.musedesk=buildMock({pending:false,polished:true});const originalEvents=window.musedesk.onChatEvent;window.musedesk.onChatEvent=fn=>{window.qaEvent=fn;return originalEvents(fn);};window.addEventListener('error',e=>document.body.dataset.error=e.message);</script>${html}`);
    browser = await openBrowser(file,path.join(dir,'profile'));
    const b = browser;
    await b.waitFor("document.querySelector('.ctx')?.textContent.includes('26%')");
    assert.equal(await b.evaluate("document.querySelectorAll('.activity-group').length"),1);
    assert.equal(await b.evaluate("document.querySelectorAll('.tool').length"),0);
    await b.evaluate("document.querySelector('.activity-head').click()");
    await b.waitFor("document.querySelectorAll('.tool').length===5");
    assert.equal(await b.evaluate("document.querySelectorAll('.reasoning-detail').length"),1);
    await b.evaluate("document.querySelector('.activity-head').click()");
    const key = async (key: string, code = key) => { await b.call('Input.dispatchKeyEvent',{type:'keyDown',key,code}); await b.call('Input.dispatchKeyEvent',{type:'keyUp',key,code}); };
    await b.evaluate("document.querySelector('[aria-label=\"Reasoning effort\"]').focus()");
    await key('ArrowDown'); await b.waitFor("document.activeElement?.classList.contains('popup-menu')");
    assert.equal(await b.evaluate("document.querySelector('.popup-menu').getBoundingClientRect().bottom <= innerHeight"),true);
    await key('End'); await key('Enter');
    await b.waitFor("document.querySelector('[aria-label=\"Reasoning effort\"]').textContent.includes('Max')");
    await b.evaluate("document.querySelector('[aria-label=Model]').click()");
    await b.waitFor("document.activeElement?.classList.contains('popup-menu')");
    await key('ArrowDown'); await key('Enter');
    await b.waitFor("document.querySelector('[aria-label=Model]').textContent.includes('demo-lite')");
    await b.evaluate("document.querySelector('[aria-label=\"More actions\"]').click()");
    await b.waitFor("document.activeElement?.classList.contains('popup-menu')");
    await key('Escape');
    assert.equal(await b.evaluate("document.activeElement?.getAttribute('aria-label')"),'More actions');
    const setDraft = async (value: string) => b.evaluate(`(()=>{const el=document.querySelector('.composer textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    await b.evaluate(`window.musedesk.pickImages=async()=>[{id:'qa-image',name:'pixel.png',mediaType:'image/png',sizeBytes:68,dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l8UAAAAASUVORK5CYII='}];document.querySelector('[aria-label="Attach images"]').click()`);
    await b.waitFor("document.querySelectorAll('.thumb').length===1");
    await setDraft('Draft in chat A');
    await b.evaluate("document.querySelectorAll('.sess-row')[1].click()");
    await b.waitFor("document.querySelector('.conv-title').textContent==='Bağlantı kurtarma'");
    assert.equal(await b.evaluate("document.querySelector('.composer textarea').value"),'');
    assert.equal(await b.evaluate("document.querySelectorAll('.thumb').length"),0);
    await setDraft('Draft in chat B');
    await b.evaluate("document.querySelectorAll('.sess-row')[0].click()");
    await b.waitFor("document.querySelector('.composer textarea').value==='Draft in chat A'");
    assert.equal(await b.evaluate("document.querySelectorAll('.thumb').length"),1);
    // A delayed send failure restores to its original chat, keeping the draft being edited elsewhere.
    await b.evaluate("window.musedesk.sendTurn=()=>new Promise((_,reject)=>{window.qaReject=reject;});document.querySelector('[aria-label=\"Send message\"]').click()");
    await b.waitFor("!!window.qaReject");
    await b.evaluate("document.querySelectorAll('.sess-row')[1].click()");
    await b.waitFor("document.querySelector('.conv-title').textContent==='Bağlantı kurtarma'");
    await b.evaluate("window.qaReject(new Error('QA delayed send failure'))");
    await b.waitFor("document.querySelector('.banner.error')?.textContent.includes('QA delayed')");
    assert.equal(await b.evaluate("document.querySelector('.composer textarea').value"),'Draft in chat B');
    await b.evaluate("document.querySelectorAll('.sess-row')[0].click()");
    await b.waitFor("document.querySelector('.composer textarea').value==='Draft in chat A'");
    assert.equal(await b.evaluate("document.querySelectorAll('.thumb').length"),1);
    await b.evaluate("Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text)=>{window.qaCopied=text}},configurable:true});document.querySelector('[aria-label=\"Copy answer\"]').click()");
    await b.waitFor("!!window.qaCopied");
    assert.equal(await b.evaluate<boolean>("window.qaCopied.includes('Okunaklı sohbet') && !window.qaCopied.includes('Evet, bu çok daha iyi.')"),true);
    await b.evaluate("document.querySelector('[aria-label=\"Like answer (this device only)\"]').click()");
    assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('musedesk.likes')).length"),1);
    await b.evaluate("document.querySelector('[aria-label=\"Remove like (this device only)\"]').click()");
    assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('musedesk.likes')).length"),0);
    for (const [width,height] of [[960,640],[1280,800],[1440,900],[1920,1080]]) {
      await b.resize(width,height);
      assert.equal(await b.evaluate("document.documentElement.scrollWidth<=innerWidth"),true,`horizontal overflow at ${width}`);
      assert.equal(await b.evaluate("document.querySelector('.composer').getBoundingClientRect().bottom<=innerHeight"),true,`composer at ${width}`);
      assert.equal(await b.evaluate("document.querySelector('.top-actions').getBoundingClientRect().right<=innerWidth"),true,`header at ${width}`);
    }
    await b.resize(960,640);
    await b.evaluate("document.querySelector('[aria-label=Changes]').click()");
    await b.waitFor("!!document.querySelector('.change-row')");
    assert.equal(await b.evaluate("document.querySelector('.main').inert"),true);
    await b.evaluate("document.querySelector('.change-row').click()"); await b.waitFor("!!document.querySelector('.diff')");
    await key('Escape'); await b.waitFor("!document.querySelector('.sidepanel')");
    assert.equal(await b.evaluate("document.querySelector('.main').inert"),false);
    await b.evaluate("document.querySelector('[aria-label=\"Hide sidebar\"]').click()");
    await b.waitFor("!!document.querySelector('[aria-label=\"Show sidebar\"]')");
    await b.evaluate("document.querySelector('[aria-label=\"Show sidebar\"]').click();document.querySelector('[aria-label=\"Open command palette\"]').click()");
    await b.waitFor("document.activeElement?.classList.contains('palette-input')");
    await key('Escape'); await b.waitFor("!document.querySelector('.dialog')");
    await b.evaluate("document.querySelector('.side-footer .side-nav-item').click()");
    await b.waitFor("!!document.querySelector('[role=dialog]')");
    await b.evaluate("document.querySelector('.dlg-actions button').focus()");
    await key('Tab');
    assert.equal(await b.evaluate("!!document.activeElement.closest('[role=dialog]')"),true);
    await key('Escape'); await b.waitFor("!document.querySelector('.dialog')");
    await b.evaluate(`window.musedesk.sendTurn=async()=>({turnId:'qa-queued',commandId:'qa-command',disposition:'queued'});window.qaEvent({sessionId:sessionA().sessionId,method:'turn/started',params:{turnId:'qa-running',viewCursor:'qa-running'}});`);
    await b.waitFor("!!document.querySelector('[aria-label=\"Stop turn\"]')");
    await b.evaluate(`const scroller=document.querySelector('.chat');scroller.dispatchEvent(new WheelEvent('wheel',{deltaY:-1000,bubbles:true}));scroller.scrollTop=0;`);
    await b.waitFor("document.querySelector('.chat').scrollTop===0 && !!document.querySelector('.jump-latest')");
    await b.evaluate(`window.qaEvent({sessionId:sessionA().sessionId,method:'item/completed',params:{item:{itemId:'qa-stream',turnId:'qa-running',kind:'agentMessage',status:'completed',revision:1,text:'A new streamed response'},viewCursor:'qa-stream'}})`);
    await b.waitFor("document.querySelector('.chat').textContent.includes('A new streamed response')");
    assert.equal(await b.evaluate("document.querySelector('.chat').scrollTop<2"),true,'new messages must not pull a reader away from history');
    await b.evaluate("document.querySelector('[aria-label=\"Queue follow-up\"]').click()");
    await b.waitFor("document.querySelector('.queued-row')?.textContent.includes('Draft in chat A')");
    await b.evaluate(`window.qaEvent({sessionId:sessionA().sessionId,method:'turn/completed',params:{turnId:'qa-running',terminal:'cancelled',viewCursor:'qa-stopped'}})`);
    await b.waitFor("document.querySelector('.turn-status.cancelled')?.textContent.includes('Turn stopped')");
    assert.equal(await b.evaluate("!!document.querySelector('.turn-status.running')"),false);
    await b.evaluate(`const statusReader=window.musedesk.getStatus;window.musedesk.getStatus=async()=>({...await statusReader(),state:'error',error:'QA offline'});window.qaEvent({sessionId:sessionA().sessionId,method:'turn/started',params:{turnId:'qa-offline',viewCursor:'qa-offline-start'}});window.qaEvent({sessionId:sessionA().sessionId,method:'item/started',params:{item:{itemId:'qa-offline-tool',turnId:'qa-offline',kind:'toolCall',status:'inProgress',revision:1,tool:'read_file'},viewCursor:'qa-offline-tool'}})`);
    await b.waitFor("document.querySelector('.activity-group.offline')?.textContent.includes('Bağlantı kesildi')");
    assert.equal(await b.evaluate("document.querySelectorAll('.activity-group.completed').length"),1,'disconnect must not relabel finished history as stopped');
    assert.equal(await b.evaluate("!!document.querySelector('.activity-group.offline .spinner')"),false);
    assert.equal(await b.evaluate("document.body.dataset.error"),undefined);
    assert.equal(await b.evaluate("!!document.querySelector('.changes-card')"),false);
  } finally { await browser?.close(); rmSync(dir,{recursive:true,force:true}); }
});
